---
name: Sync mirrors
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"
jobs:
  build:
    name: "Build"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          path: main

      - uses: actions/setup-go@v2
        with:
          go-version: '1.14.0'

      - name: Build
        run: |
          make
        working-directory: ./main

      - uses: actions/upload-artifact@v2
        with:
          name: service-mirrors
          path: ./main/service-mirrors

  cannahome:
    name: "CannaHome"
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: service-mirrors
          path: ./main

      - name: Update permissions
        run: |
          chmod +x service-mirrors
        working-directory: ./main

      - name: Update PATH
        run: |
          echo ::set-env name=PATH::$PATH:$GITHUB_WORKSPACE/main

      - uses: actions/checkout@v2
        with:
          repository: onionltd/oniontree
          path: oniontree

      - uses: onionltd/tor-proxy@v1

      - name: Sync
        run: |
          service-mirrors sync --timeout 1m cannahome
        env:
          http_proxy: "socks5://localhost:9050"
          https_proxy: "socks5://localhost:9050"
        working-directory: ./oniontree

      - name: Check status
        run: |
          test -z "$(git status --porcelain)"
        working-directory: ./oniontree

  aseanmarket:
    name: "ASEAN Market"
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: service-mirrors
          path: ./main

      - name: Update permissions
        run: |
          chmod +x service-mirrors
        working-directory: ./main

      - name: Update PATH
        run: |
          echo ::set-env name=PATH::$PATH:$GITHUB_WORKSPACE/main

      - uses: actions/checkout@v2
        with:
          repository: onionltd/oniontree
          path: oniontree

      - uses: onionltd/tor-proxy@v1

      - name: Sync
        run: |
          service-mirrors sync --timeout 1m aseanmarket
        env:
          http_proxy: "socks5://localhost:9050"
          https_proxy: "socks5://localhost:9050"
        working-directory: ./oniontree

      - name: Check status
        run: |
          test -z "$(git status --porcelain)"
        working-directory: ./oniontree

  yellowbrick:
    name: "Yellow Brick"
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: service-mirrors
          path: ./main

      - name: Update permissions
        run: |
          chmod +x service-mirrors
        working-directory: ./main

      - name: Update PATH
        run: |
          echo ::set-env name=PATH::$PATH:$GITHUB_WORKSPACE/main

      - uses: actions/checkout@v2
        with:
          repository: onionltd/oniontree
          path: oniontree

      - uses: onionltd/tor-proxy@v1

      - name: Sync
        run: |
          service-mirrors sync --timeout 1m yellowbrick
        env:
          http_proxy: "socks5://localhost:9050"
          https_proxy: "socks5://localhost:9050"
        working-directory: ./oniontree

      - name: Check status
        run: |
          test -z "$(git status --porcelain)"
        working-directory: ./oniontree

  torrezmarket:
    name: "ToRRez Market"
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: service-mirrors
          path: ./main

      - name: Update permissions
        run: |
          chmod +x service-mirrors
        working-directory: ./main

      - name: Update PATH
        run: |
          echo ::set-env name=PATH::$PATH:$GITHUB_WORKSPACE/main

      - uses: actions/checkout@v2
        with:
          repository: onionltd/oniontree
          path: oniontree

      - uses: onionltd/tor-proxy@v1

      - name: Sync
        run: |
          service-mirrors sync --timeout 1m torrezmarket
        env:
          http_proxy: "socks5://localhost:9050"
          https_proxy: "socks5://localhost:9050"
        working-directory: ./oniontree

      - name: Check status
        run: |
          test -z "$(git status --porcelain)"
        working-directory: ./oniontree

  canadahq:
    name: "The Canadian HQ"
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: service-mirrors
          path: ./main

      - name: Update permissions
        run: |
          chmod +x service-mirrors
        working-directory: ./main

      - name: Update PATH
        run: |
          echo ::set-env name=PATH::$PATH:$GITHUB_WORKSPACE/main

      - uses: actions/checkout@v2
        with:
          repository: onionltd/oniontree
          path: oniontree

      - uses: onionltd/tor-proxy@v1

      - name: Sync
        run: |
          service-mirrors sync --timeout 1m canadahq
        env:
          http_proxy: "socks5://localhost:9050"
          https_proxy: "socks5://localhost:9050"
        working-directory: ./oniontree

      - name: Check status
        run: |
          test -z "$(git status --porcelain)"
        working-directory: ./oniontree

  deepseamarket:
    name: "DeepSea Market"
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: service-mirrors
          path: ./main

      - name: Update permissions
        run: |
          chmod +x service-mirrors
        working-directory: ./main

      - name: Update PATH
        run: |
          echo ::set-env name=PATH::$PATH:$GITHUB_WORKSPACE/main

      - uses: actions/checkout@v2
        with:
          repository: onionltd/oniontree
          path: oniontree

      - uses: onionltd/tor-proxy@v1

      - name: Sync
        run: |
          service-mirrors sync --timeout 1m deepseamarket
        env:
          http_proxy: "socks5://localhost:9050"
          https_proxy: "socks5://localhost:9050"
        working-directory: ./oniontree

      - name: Check status
        run: |
          test -z "$(git status --porcelain)"
        working-directory: ./oniontree

  darkfoxmarket:
    name: "DarkFox Market"
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: service-mirrors
          path: ./main

      - name: Update permissions
        run: |
          chmod +x service-mirrors
        working-directory: ./main

      - name: Update PATH
        run: |
          echo ::set-env name=PATH::$PATH:$GITHUB_WORKSPACE/main

      - uses: actions/checkout@v2
        with:
          repository: onionltd/oniontree
          path: oniontree

      - uses: onionltd/tor-proxy@v1

      - name: Sync
        run: |
          service-mirrors sync --timeout 1m darkfoxmarket
        env:
          http_proxy: "socks5://localhost:9050"
          https_proxy: "socks5://localhost:9050"
        working-directory: ./oniontree

      - name: Check status
        run: |
          test -z "$(git status --porcelain)"
        working-directory: ./oniontree

  cannazon:
    name: "Cannazon"
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: service-mirrors
          path: ./main

      - name: Update permissions
        run: |
          chmod +x service-mirrors
        working-directory: ./main

      - name: Update PATH
        run: |
          echo ::set-env name=PATH::$PATH:$GITHUB_WORKSPACE/main

      - uses: actions/checkout@v2
        with:
          repository: onionltd/oniontree
          path: oniontree

      - uses: onionltd/tor-proxy@v1

      - name: Sync
        run: |
          service-mirrors sync --timeout 1m cannazon
        env:
          http_proxy: "socks5://localhost:9050"
          https_proxy: "socks5://localhost:9050"
        working-directory: ./oniontree

      - name: Check status
        run: |
          test -z "$(git status --porcelain)"
        working-directory: ./oniontree
